export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAILED = 'CHECK_AUTH_FAILED';
export const EMAIL_CHANGE_INVALID = 'EMAIL_CHANGE_INVALID';
export const EMAIL_CHANGE = 'EMAIL_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const SIGN_UP = 'SIGN_UP';

//Sign_Up

export const BACK_BUTTON_SIGNUP = 'BACK_BUTTON_SIGNUP';
export const NAME_CHANGE_SIGNUP = 'NAME_CHANGE_SIGNUP';
export const NAME_CHANGE_INVALID_SIGNUP = 'NAME_CHANGE_INVALID_SIGNUP';
export const EMAIL_CHANGE_SIGNUP = 'EMAIL_CHANGE_SIGNUP';
export const EMAIL_CHANGE_INVALID_SIGNUP = 'EMAIL_CHANGE_INVALID_SIGNUP';
export const PASSWORD_CHANGE_SIGNUP = 'PASSWORD_CHANGE_SIGNUP';
export const PASSWORD_CHANGE_INVALID_SIGNUP = 'PASSWORD_CHANGE_INVALID_SIGNUP';
export const CONFIRM_PASSWORD_CHANGE_SIGNUP = 'CONFIRM_PASSWORD_CHANGE_SIGNUP';
export const CONFIRM_PASSWORD_CHANGE_INVALID_SIGNUP =
  'CONFIRM_PASSWORD_CHANGE_INVALID_SIGNUP';
export const SIGN_UP_ATTEMPT = 'SIGN_UP_ATTEMPT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

//ForgetPassword
export const EMAIL_CHANGE_INVALID_FORGET_PASSWORD =
  'EMAIL_CHANGE_INVALID_FORGET_PASSWORD';
export const EMAIL_CHANGE_FORGET_PASSWORD = 'EMAIL_CHANGE_FORGET_PASSWORD';
export const GENERATE_CODE_SEND = 'GENERATE_CODE_SEND';
export const GENERATE_CODE_SEND_VALID = 'GENERATE_CODE_SEND_VALID';
export const GENERATE_CODE_SEND_INVALID = 'GENERATE_CODE_SEND_INVALID';

//ChangePassword
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const BUTTON_UPDATE_PASSWORD = 'BUTTON_UPDATE_PASSWORD';
export const BUTTON_UPDATE_PASSWORD_SUCCESS = 'BUTTON_UPDATE_PASSWORD_SUCCESS';
export const BUTTON_UPDATE_PASSWORD_FAILED = 'BUTTON_UPDATE_PASSWORD_FAILED';
export const PASSWORD_CHANGE_CHANGE_SCREEN = 'PASSWORD_CHANGE_CHANGE_SCREEN';
export const PASSWORD_CHANGE_INVALID_CHANGE_SCREEN = 'PASSWORD_CHANGE_INVALID_CHANGE_SCREEN';
export const PASSWORD_CHANGE_CONFIRM_VALID_CHANGE_SCREEN =
  'PASSWORD_CHANGE_CONFIRM_VALID_CHANGE_SCREEN';
export const PASSWORD_CHANGE_CONFIRM_INVALID_CHANGE_SCREEN =
  'PASSWORD_CHANGE_CONFIRM_INVALID_CHANGE_SCREEN';

//Home
export const LOAD_DATE_SUCCESS = 'LOAD_DATE_SUCCESS';
export const LOAD_DATE_FAILED = 'LOAD_DATE_FAILED';
export const REFRESH_DATA_VALUE = 'REFRESH_DATA_VALUE';
export const REFRESH_DATA_TRUE = 'REFRESH_DATA_TRUE';
export const REFRESH_DATA_FALSE = 'REFRESH_DATA_FALSE';

//DownloadFile
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';

//QrCodeScan
export const START_SCAN_QR_CODE = 'START_SCAN_QR_CODE';
export const SCAN_DONE = 'SCAN_DONE';

//Payment
export const SEND_PAY = 'SEND_PAY';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILED = 'PAYMENT_FAILED';